// Continuous Native Generation config (N0b-1).
//
// `android/` is generated by `expo prebuild` and is NOT tracked: everything
// that shapes the native project has to be expressible here, so the day N2
// needs a custom backup-rules plugin there is no hand-edited Gradle file
// arguing with it.

import type { ExpoConfig } from 'expo/config';

const config: ExpoConfig = {
  name: 'lark spike',
  slug: 'lark-spike-mobile-foundation',
  version: '0.0.0',
  orientation: 'portrait',
  platforms: ['android'],
  // The share-intent plugin refuses to configure itself without one, and the
  // hook reads it back through expo-constants. Spike-flavoured on purpose, for
  // the same reason the applicationId is: a scheme is something other apps can
  // link to, and the product's belongs to the product.
  scheme: 'larkspike',
  // DELIBERATELY NOT `com.orpheusaviary.lark`. That id belongs to the product
  // APK (D14, criterion 25); a spike wearing it would sit on the device as the
  // real app's predecessor, and the first real install would inherit its data
  // directory — including whatever half-finished SecureStore entries the D16
  // experiments left behind.
  android: {
    package: 'com.orpheusaviary.lark.spike',
    // POST_NOTIFICATIONS is what makes the media notification VISIBLE on
    // Android 13+ (the foreground service runs either way, but a denied
    // permission keeps its notification out of the drawer) — and the lock
    // screen controls ARE that notification. Criterion 19 asks for them.
    permissions: ['android.permission.POST_NOTIFICATIONS'],
    // D16, criterion 26. This turns off cloud backup; it does NOT turn off
    // device-to-device transfer on Android 12+, which is what the rule files
    // in `plugins/with-backup-rules.js` are for.
    allowBackup: false,
  },
  plugins: [
    [
      // Background playback: the plugin adds FOREGROUND_SERVICE +
      // FOREGROUND_SERVICE_MEDIA_PLAYBACK and registers the media3
      // MediaSessionService. Recording is switched off — the spike never
      // records, and a spike that asks for the microphone is a spike that gets
      // a permission dialog nobody understands.
      'expo-audio',
      { recordAudioAndroid: false, enableBackgroundPlayback: true },
    ],
    [
      // Criterion 24: receive what the bilibili app sends. The plugin adds an
      // ACTION_SEND filter to MainActivity and switches it to singleTask, so a
      // share arriving while the app is already alive comes through
      // onNewIntent rather than starting a second copy of it.
      //
      // `text/*` is the plugin default, spelled out because it IS the
      // criterion: bilibili shares text/plain, and every extra mime type here
      // is another entry lark would appear under in the share sheet.
      //
      // `disableIOS` because this spike is `platforms: ['android']` — the iOS
      // half builds a share-extension Xcode target (and wants a patched
      // `xcode` package for it), none of which should exist here.
      'expo-share-intent',
      { androidIntentFilters: ['text/*'], disableIOS: true },
    ],
    [
      // D16 (criterion 26): expo-secure-store installs its own backup rules by
      // default, pointing the two manifest attributes at ITS xml files. Ours
      // have to be the only ones — see `plugins/with-backup-rules.js`, which
      // throws rather than overwrite a value it did not write.
      'expo-secure-store',
      { configureAndroidBackup: false },
    ],
    './plugins/with-backup-rules',
    [
      'expo-build-properties',
      {
        android: {
          // target 36 per the master plan's D14. The frozen measurement device
          // runs API 35, so anything gated on the DEVICE being Android 16 is
          // out of reach here — see the subplan §9 device dossier.
          compileSdkVersion: 36,
          targetSdkVersion: 36,
          buildToolsVersion: '36.0.0',
          // SPIKE-ONLY (decision f): the probes talk to a LAN skybridge server
          // over plaintext HTTP. The product line stays https-only and TLS is
          // due at N4 (D15) — this lives here, in one line, so that revoking
          // it is deleting one line rather than auditing a manifest.
          usesCleartextTraffic: true,
        },
      },
    ],
  ],
};

export default config;
