// Continuous Native Generation config (N0b-1).
//
// `android/` is generated by `expo prebuild` and is NOT tracked: everything
// that shapes the native project has to be expressible here, so the day N2
// needs a custom backup-rules plugin there is no hand-edited Gradle file
// arguing with it.

import type { ExpoConfig } from 'expo/config';

const config: ExpoConfig = {
  name: 'lark spike',
  slug: 'lark-spike-mobile-foundation',
  version: '0.0.0',
  orientation: 'portrait',
  platforms: ['android'],
  // DELIBERATELY NOT `com.orpheusaviary.lark`. That id belongs to the product
  // APK (D14, criterion 25); a spike wearing it would sit on the device as the
  // real app's predecessor, and the first real install would inherit its data
  // directory — including whatever half-finished SecureStore entries the D16
  // experiments left behind.
  android: {
    package: 'com.orpheusaviary.lark.spike',
    // POST_NOTIFICATIONS is what makes the media notification VISIBLE on
    // Android 13+ (the foreground service runs either way, but a denied
    // permission keeps its notification out of the drawer) — and the lock
    // screen controls ARE that notification. Criterion 19 asks for them.
    permissions: ['android.permission.POST_NOTIFICATIONS'],
  },
  plugins: [
    [
      // Background playback: the plugin adds FOREGROUND_SERVICE +
      // FOREGROUND_SERVICE_MEDIA_PLAYBACK and registers the media3
      // MediaSessionService. Recording is switched off — the spike never
      // records, and a spike that asks for the microphone is a spike that gets
      // a permission dialog nobody understands.
      'expo-audio',
      { recordAudioAndroid: false, enableBackgroundPlayback: true },
    ],
    [
      'expo-build-properties',
      {
        android: {
          // target 36 per the master plan's D14. The frozen measurement device
          // runs API 35, so anything gated on the DEVICE being Android 16 is
          // out of reach here — see the subplan §9 device dossier.
          compileSdkVersion: 36,
          targetSdkVersion: 36,
          buildToolsVersion: '36.0.0',
          // SPIKE-ONLY (decision f): the probes talk to a LAN skybridge server
          // over plaintext HTTP. The product line stays https-only and TLS is
          // due at N4 (D15) — this lives here, in one line, so that revoking
          // it is deleting one line rather than auditing a manifest.
          usesCleartextTraffic: true,
        },
      },
    ],
  ],
};

export default config;
