// Continuous Native Generation config (N2a).
//
// `android/` is generated by `expo prebuild` and is NOT tracked: everything
// that shapes the native project has to be expressible here, so a config
// plugin is the only thing that can ever argue with it. The spike proved this
// arrangement (N0b-1); this is the product wearing it.

import type { ExpoConfig } from 'expo/config';

const config: ExpoConfig = {
  name: 'Lark',
  slug: 'lark',
  // D14's independent APK version line — NOT the desktop's 0.3.0. The two ship
  // separately and a shared number would only ever be a coincidence.
  version: '0.1.0',
  orientation: 'portrait',
  platforms: ['android'],
  scheme: 'lark',
  android: {
    // D14 (N0b-5b): this id and the `lark-release.jks` keystore are what the
    // Play policy snapshot registers, and it is deliberately NOT the spike's
    // `…lark.spike` — sharing one would have the first real install inherit
    // the spike's data directory, half-finished SecureStore entries included.
    package: 'com.orpheusaviary.lark',
    versionCode: 1,
    // N3a. POST_NOTIFICATIONS is what makes the media notification VISIBLE on
    // Android 13+ — and on Android 13+ that notification IS the lock screen
    // controls. The foreground service runs either way, so a denied permission
    // does not stop playback; it just leaves the lock screen empty, which is
    // exactly how N0b-4b's first soak failed. Declaring it here is half the
    // job: `requestNotificationPermissionsAsync()` still has to ask at run
    // time (`player/session.ts`).
    permissions: ['android.permission.POST_NOTIFICATIONS'],
    // D16 (criteria 16a/16b). This turns off cloud backup; it does NOT turn
    // off device-to-device transfer on Android 12+, which is what the rule
    // files in `plugins/with-backup-rules.js` are for.
    allowBackup: false,
  },
  plugins: [
    [
      // N3a. `enableBackgroundPlayback` is what adds FOREGROUND_SERVICE +
      // FOREGROUND_SERVICE_MEDIA_PLAYBACK and registers media3's
      // MediaSessionService; without it Android stops background playback
      // after about three minutes.
      //
      // `recordAudioAndroid: false` is not a preference. The plugin's default
      // asks for RECORD_AUDIO, and a music player that wants the microphone is
      // a permission dialog nobody understands. Criterion 3b asserts both
      // halves against the BUILT apk's merged manifest rather than against
      // this file, because this is the kind of line an SDK upgrade changes
      // quietly.
      'expo-audio',
      { recordAudioAndroid: false, enableBackgroundPlayback: true },
    ],
    [
      // D16: expo-secure-store installs its own backup rules by default,
      // pointing the two manifest attributes at ITS xml files. Ours have to be
      // the only ones — see `plugins/with-backup-rules.js`, which throws
      // rather than overwrite a value it did not write (N0b-5a measured this
      // one: two plugins writing the same attribute is the failure where the
      // last one wins and nobody notices).
      'expo-secure-store',
      { configureAndroidBackup: false },
    ],
    './plugins/with-backup-rules',
    [
      'expo-build-properties',
      {
        android: {
          // target 36 per the master plan's D14. The frozen measurement device
          // runs API 35, so anything gated on the DEVICE being Android 16 is
          // out of reach — N0 subplan §9 records that gap.
          compileSdkVersion: 36,
          targetSdkVersion: 36,
          buildToolsVersion: '36.0.0',
          // Decision a, closed 2026-08-19. `writeTextAtomic`'s contract needs
          // `Files.move(…, ATOMIC_MOVE)`, which is NIO and therefore API 26+ —
          // and expo-file-system's own module is `@RequiresApi(O)` anyway
          // (`FileSystemModule.kt:32`), so a 24 floor was already a fiction on
          // the one path lark cannot weaken. Criterion 10⑤ asserts this
          // against the BUILT apk's merged manifest, not against this line.
          minSdkVersion: 26,
        },
      },
    ],
  ],
};

export default config;
