// Continuous Native Generation config (N2a).
//
// `android/` is generated by `expo prebuild` and is NOT tracked: everything
// that shapes the native project has to be expressible here, so a config
// plugin is the only thing that can ever argue with it. The spike proved this
// arrangement (N0b-1); this is the product wearing it.

import type { ExpoConfig } from 'expo/config';

const config: ExpoConfig = {
  name: 'Lark',
  slug: 'lark',
  // D14's independent APK version line — NOT the desktop's 0.3.0. The two ship
  // separately and a shared number would only ever be a coincidence.
  version: '0.2.2',
  orientation: 'portrait',
  platforms: ['android'],
  scheme: 'lark',
  // The launcher icon. 0.1.0's first upload shipped Expo's placeholder and was
  // replaced in place the same day — nothing offline could see it, because a
  // missing `icon` is not an error: the template has a default and prebuild
  // uses it without a word.
  //
  // Both files are derived from the desktop's
  // `packages/gui/resources/lark-icon-source.png` — the artwork with its opaque
  // grey halo already cut away. They are committed artifacts, not build output
  // (prebuild reads them), and `assets/README.md` carries the recipe that made
  // them, the same way `packages/gui/scripts/build-icons.mjs` carries the one
  // that made its source.
  icon: './assets/icon.png',
  android: {
    // D14 (N0b-5b): this id and the `lark-release.jks` keystore are what the
    // Play policy snapshot registers, and it is deliberately NOT the spike's
    // `…lark.spike` — sharing one would have the first real install inherit
    // the spike's data directory, half-finished SecureStore entries included.
    package: 'com.orpheusaviary.lark',
    versionCode: 5,
    // N3a. POST_NOTIFICATIONS is what makes the media notification VISIBLE on
    // Android 13+ — and on Android 13+ that notification IS the lock screen
    // controls. The foreground service runs either way, so a denied permission
    // does not stop playback; it just leaves the lock screen empty, which is
    // exactly how N0b-4b's first soak failed. Declaring it here is half the
    // job: `requestNotificationPermissionsAsync()` still has to ask at run
    // time (`player/session.ts`).
    permissions: ['android.permission.POST_NOTIFICATIONS'],
    // D16 (criteria 16a/16b). This turns off cloud backup; it does NOT turn
    // off device-to-device transfer on Android 12+, which is what the rule
    // files in `plugins/with-backup-rules.js` are for.
    allowBackup: false,
    // Android 8+ masks every icon into the launcher's own shape, and minSdk is
    // 26 — so THIS is the icon on every device lark supports; `icon` above is
    // only the legacy fallback and the notification base.
    //
    // The foreground spans exactly the inner 72 of 108dp: that is the safe
    // zone, so a circular mask, a squircle and a rounded square all show the
    // whole scene rather than clipping the wordmark off the bottom. The
    // background is the artwork's own dark outline colour (sampled), so what
    // the mask leaves at the corners looks like part of the tile instead of a
    // slab behind it.
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#0b332f',
    },
  },
  plugins: [
    [
      // N3a. `enableBackgroundPlayback` is what adds FOREGROUND_SERVICE +
      // FOREGROUND_SERVICE_MEDIA_PLAYBACK and registers media3's
      // MediaSessionService; without it Android stops background playback
      // after about three minutes.
      //
      // `recordAudioAndroid: false` is not a preference. The plugin's default
      // asks for RECORD_AUDIO, and a music player that wants the microphone is
      // a permission dialog nobody understands. Criterion 3b asserts both
      // halves against the BUILT apk's merged manifest rather than against
      // this file, because this is the kind of line an SDK upgrade changes
      // quietly.
      'expo-audio',
      { recordAudioAndroid: false, enableBackgroundPlayback: true },
    ],
    [
      // N4d: receive what the bilibili app sends (criterion 22). The plugin
      // adds an ACTION_SEND filter to MainActivity and switches its launchMode
      // to singleTask, so a share arriving while the app is already alive comes
      // through `onNewIntent` rather than starting a second copy of it — which
      // matters more here than it did in the spike, because this app has a boot
      // sequence that must run exactly once per process (`bootOnce`).
      //
      // `text/*` is the plugin default, spelled out because it IS the
      // criterion: bilibili shares text/plain, and every extra mime type here
      // is another entry lark would appear under in the share sheet.
      //
      // `disableIOS` because this app is `platforms: ['android']` — the iOS
      // half builds a share-extension Xcode target (and wants a patched `xcode`
      // package for it), none of which should exist here.
      'expo-share-intent',
      { androidIntentFilters: ['text/*'], disableIOS: true },
    ],
    [
      // D16: expo-secure-store installs its own backup rules by default,
      // pointing the two manifest attributes at ITS xml files. Ours have to be
      // the only ones — see `plugins/with-backup-rules.js`, which throws
      // rather than overwrite a value it did not write (N0b-5a measured this
      // one: two plugins writing the same attribute is the failure where the
      // last one wins and nobody notices).
      'expo-secure-store',
      { configureAndroidBackup: false },
    ],
    './plugins/with-backup-rules',
    // N6d, criterion 95. Expo's template signs the RELEASE build with the
    // Android debug key and leaves a comment about it; `android/` is generated
    // and untracked, so the only place that can be fixed is here.
    './plugins/with-release-signing',
    [
      'expo-build-properties',
      {
        android: {
          // target 36 per the master plan's D14. The frozen measurement device
          // runs API 35, so anything gated on the DEVICE being Android 16 is
          // out of reach — N0 subplan §9 records that gap.
          compileSdkVersion: 36,
          targetSdkVersion: 36,
          buildToolsVersion: '36.0.0',
          // N5b, master plan §4.3 Stage-4 (user decision, 2026-08-25). D15
          // used to say mobile v1 is https-only, and this line's ABSENCE was
          // how that was enforced — Android 9+ refuses cleartext by default.
          // lark now supports both schemes with one switch in settings
          // (`local_metadata.sync_allow_insecure`), because other people run
          // their own skybridge on a bare IP and "open one host" is not
          // available to us: a networkSecurityConfig allowlist is compile-time
          // XML, and the hosts belong to whoever installs this.
          //
          // THE COST, spelled out so nobody has to rediscover it: this is
          // app-wide. bilibili's audio streams, the lyrics providers and a
          // user-supplied LLM endpoint all lose the platform's https floor
          // with it. That was part of the same decision (N5 subplan §0.1), and
          // it is why `src/acceptance/downloads.ts` no longer claims criterion
          // 5's second half proves anything.
          usesCleartextTraffic: true,
          // Decision a, closed 2026-08-19. `writeTextAtomic`'s contract needs
          // `Files.move(…, ATOMIC_MOVE)`, which is NIO and therefore API 26+ —
          // and expo-file-system's own module is `@RequiresApi(O)` anyway
          // (`FileSystemModule.kt:32`), so a 24 floor was already a fiction on
          // the one path lark cannot weaken. Criterion 10⑤ asserts this
          // against the BUILT apk's merged manifest, not against this line.
          minSdkVersion: 26,
        },
      },
    ],
  ],
};

export default config;
