// GENERATED by scripts/make-desktop-fixtures.mjs — do not edit by hand.
//
// Expected values computed on the DESKTOP by the implementations core actually
// calls (`node:crypto`, `Buffer`). The device compares against these; a device
// that generated its own expectations would only be agreeing with itself.

export interface DigestFixture {
  /** Built as `seed.repeat(repeats)` on both sides. */
  seed: string;
  repeats: number;
  bytes: number;
  md5?: string;
  sha256: string;
}

export const WBI_QUERY =
  'bvid=BV1xx411c7mD&cid=1234567890&fnval=4048&fnver=0&fourk=1&otype=json&platform=pc&qn=0&wts=17000000007cd084941338484aae1ad9425b84077c4932caff0ff746eab6f01bf08b70ac45';
export const WBI_QUERY_MD5 = '802b8efb9268663f67fdabcdd3389975';
export const WBI_QUERY_SHA256 = '6d3e05fed1d76d780e0d997a18ec8e0a1e42a8f42cafcbf5b24b5dce181b23f3';

export const LYRICS_4K: DigestFixture = {
  seed: '[00:12.34]床前明月光，疑是地上霜 — a bilingual lyric line\n',
  repeats: 80,
  bytes: 5680,
  md5: 'b0f2d5b2cf3ed61406d5a61edb500c17',
  sha256: 'e370952b61f45bb8977ca92124aff7e94d5793b185f9d909c49c0b5994fa3ce3',
};

export const BULK_256K: DigestFixture = {
  seed: 'lark-lark-lark-lark-lark-lark-lark-lark-lark-lark-lark-lark-lark-',
  repeats: 4033,
  bytes: 262145,
  sha256: '5c3937aade5906e551cf07da090798fd492b9330a1f374b10f03603e48e973fa',
};

export interface Utf8Fixture {
  name: string;
  text: string;
  /** `Buffer.byteLength(text, 'utf8')` on the desktop. */
  bytes: number;
}

export const UTF8_FIXTURES: readonly Utf8Fixture[] = [
  {
    name: 'ascii',
    text: 'plain ascii payload',
    bytes: 19,
  },
  {
    name: 'chinese',
    text: '歌曲名字与艺人',
    bytes: 21,
  },
  {
    name: 'surrogate pair',
    text: '🎵🎧🎼',
    bytes: 12,
  },
  {
    name: 'combining marks',
    text: 'é à ñ',
    bytes: 11,
  },
  {
    name: 'lone surrogate',
    text: 'before\ud83dafter',
    bytes: 14,
  },
  {
    name: 'mixed json',
    text: '{"name":"歌曲 🎵","artist":"Ärtist"}',
    bytes: 41,
  },
];

export interface Base64Fixture {
  name: string;
  input: string;
  /** What `Buffer.from(input, 'base64')` produced, hex-encoded. */
  bytesHex: string;
  /** …and the same bytes decoded as UTF-8, which is what `decodeBase64` returns. */
  utf8: string;
}

export const BASE64_FIXTURES: readonly Base64Fixture[] = [
  {
    name: 'padded',
    input: '5bqK5YmN5piO5pyI5YWJ',
    bytesHex: 'e5ba8ae5898de6988ee69c88e58589',
    utf8: '床前明月光',
  },
  {
    name: 'unpadded',
    input: '5bqK5YmN5piO5pyI5YWJ',
    bytesHex: 'e5ba8ae5898de6988ee69c88e58589',
    utf8: '床前明月光',
  },
  {
    name: 'newlines inside',
    input: 'bHly\naWNzIGxpbmU=',
    bytesHex: '6c7972696373206c696e65',
    utf8: 'lyrics line',
  },
  {
    name: 'illegal character',
    input: 'aGVs!bG8=',
    bytesHex: '68656c6c6f',
    utf8: 'hello',
  },
  {
    name: 'url-safe alphabet',
    input: '-_-_',
    bytesHex: 'fbffbf',
    utf8: '���',
  },
  {
    name: 'length 1 mod 4',
    input: 'aGVsbG8X',
    bytesHex: '68656c6c6f17',
    utf8: 'hello\u0017',
  },
  {
    name: 'empty',
    input: '',
    bytesHex: '',
    utf8: '',
  },
];
